# Generated by Django 3.2.9 on 2021-12-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.CharField(blank=True, max_length=5)),
                ('close_time', models.CharField(blank=True, max_length=5)),
                ('major', models.CharField(blank=True, max_length=15)),
                ('location', models.CharField(max_length=45)),
                ('spell', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.CharField(blank=True, max_length=5)),
                ('close_time', models.CharField(blank=True, max_length=5)),
                ('location', models.CharField(max_length=45)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.building')),
            ],
        ),
    ]
