# Generated by Django 3.2.9 on 2021-12-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20211204_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['name']},
        ),
    ]
