# Generated by Django 3.2.9 on 2021-12-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20211204_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='major',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
