# Generated by Django 3.2.9 on 2021-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_building_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='tel',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='facility',
            name='tel',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
