# Generated by Django 3.2.9 on 2021-12-04 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('stars', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagOnReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Review.review')),
            ],
        ),
    ]
